name: Build push and deploy image

on:
  workflow_dispatch
  #push:
  #  branches: [main]
  #pull_request:
  #  branches: [main]
env:
  AWS_REGION: us-east-1
  AWS_ROLE: ${{ secrets.AWS_ACTION_ROLE }}


jobs: 
  build: 
    runs-on: ubuntu-latest #github or share runner
    steps:
      - name: clone repo #clone the repo
        uses: actions/checkout@v3  # actions 
      - name: Aws creds config # loging to aws 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_REGION }}             # OIDC  
          aws-region: ${{ env.AWS_REGION }}
      - name: loging to ecr
        uses: aws-actions/amazon-ecr-login@v1